blank_issues_enabled: true
contact_links:
  - name: "💬 Сайттағы пікір формасы"
    url: https://mustafa7677.github.io/CS50MUSS/
    about: Кез келген беттің төменгі жағындағы «Пікір қалдыру» сілтемесі
